CoffeeCo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('Coffee_Co.urls')),
]

Coffee_Co/urls.py
'''Defines URL patterns for Coffee_Co'''
from django.urls import path
from . import views

app_name = 'Coffee_Co'
urlpatterns = [
    #Home Page
    path('', views.index, name = 'index'),
    #Page that shows all Coffee Types
    path('coffeeType/', views.coffeeTypes, name='coffeeTypes'),
    #Page for a singular Coffee Type
    path('coffeeType/<int:coffeeType_id>/', views.coffeeType, name='coffeeType'),
    #Page for adding a new Coffee Type
    path('newCoffeeType', views.newCoffeeType, name = 'newCoffeeType'),
    #Page for adding a new Coffee Recipe
    path('new_recipe/<int:coffeeType_id>/', views.newCoffeeRecipe, name = 'newCoffeeRecipe'),
    #Page for editing a Coffee Recipe
    path('edit_recipe/<int:recipe_id>/', views.editCoffeeRecipe, name='editCoffeeRecipe'),
    #General Information Page
    path('coffee-info/', views.coffee_info, name='coffeeInfo'),
]

users/urls.py
'''Defines URL Patterns for Users'''
from django.urls import path, include
from .import views

app_name = 'users'
urlpatterns = [
    #Include Default Auth Urls.
    path('', include('django.contrib.auth.urls')),
    #Registration Page
    path('register/', views.register, name = 'register'),
]

Coffee_Co/models.py
from django.db import models
from django.contrib.auth.models import User


class CoffeeType(models.Model):
    '''The type of coffee the user is recording about'''
    text = models.CharField(max_length = 200)
    date_added = models.DateTimeField(auto_now_add = True)
    owner = models.ForeignKey(User, on_delete = models.CASCADE)

    class Meta:
        verbose_name = "Coffee Type"

    def __str__(self):
        '''Return a string representation of the model'''
        return self.text

class CoffeeRecipeEntry(models.Model):
    '''A recipe for a chosen CoffeeType e.g (Latte Recipe)'''
    coffeeType = models.ForeignKey(CoffeeType, on_delete = models.CASCADE)
    text = models.TextField()
    rating = models.IntegerField(choices=[(i, str(i)) for i in range(1, 6)])
    date_added = models.DateTimeField(auto_now_add = True)

    class Meta:
        verbose_name_plural = 'Coffee Recipe Entries'

    def __str__(self):
        '''Return a string representation of the model'''
        return f"{self.text[:50]}"

users/models.py
from django.db import models

# Create your models here.

Coffee_Co/forms.py
from django import forms
from .models import CoffeeType, CoffeeRecipeEntry

class CoffeeTypeForm(forms.ModelForm):
    class Meta:
        model = CoffeeType
        fields = ['text']
        labels = {'text': ''}

class CoffeeRecipeEntryForm(forms.ModelForm):
    rating = forms.ChoiceField(
        choices=[(i, str(i)) for i in range(1, 6)],
        widget=forms.RadioSelect,
        required=True,
    )

    class Meta:
        model = CoffeeRecipeEntry
        fields = ['text', 'rating']
        labels = {'text': 'Entry:'}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

Coffee_Co/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import CoffeeType, CoffeeRecipeEntry
from .forms import CoffeeTypeForm, CoffeeRecipeEntryForm
from django.contrib.auth.decorators import login_required
from django.http import Http404

def index(request):
    '''The home page for CoffeeCo'''
    return render(request, 'Coffee_Co/index.html')

@login_required
def coffeeTypes(request):
    '''Shows all Coffee Types and its entries'''
    coffeeTypes = CoffeeType.objects.filter(owner = request.user).order_by('date_added')
    context = {'coffeeTypes': coffeeTypes}
    return render(request, 'Coffee_Co/coffeeTypes.html', context)

@login_required
def coffeeType(request, coffeeType_id):
    '''Show a single Coffee Type and its entries'''
    coffeeType = get_object_or_404(CoffeeType, id=coffeeType_id)

    if coffeeType.owner != request.user:
        raise Http404

    entries = coffeeType.coffeerecipeentry_set.order_by('-date_added')
    context = {'coffeeType': coffeeType, 'entries': entries}
    return render(request, 'Coffee_Co/coffeeType.html', context)

@login_required
def newCoffeeType(request):
    '''Add a new coffee type'''
    if request.method != 'POST':
        form = CoffeeTypeForm()
    else:
        form = CoffeeTypeForm(data=request.POST)
        if form.is_valid():
            coffee_type = form.save(commit=False)
            coffee_type.owner = request.user
            coffee_type.save()
            return redirect('Coffee_Co:coffeeTypes')

    context = {'form': form}
    return render(request, 'Coffee_Co/newCoffeeType.html', context)

@login_required
def newCoffeeRecipe(request, coffeeType_id):
    '''Add a new recipe for a Coffee Type'''
    coffeeType = CoffeeType.objects.get(id=coffeeType_id)

    if request.method != 'POST':
        form = CoffeeRecipeEntryForm()
    else:
        form = CoffeeRecipeEntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.coffeeType = coffeeType
            new_entry.save()
            return redirect('Coffee_Co:coffeeType', coffeeType_id=coffeeType_id)

    context = {'coffeeType': coffeeType, 'form': form}
    return render(request, 'Coffee_Co/newCoffeeRecipe.html', context)

@login_required
def editCoffeeRecipe(request, recipe_id):
    recipe = CoffeeRecipeEntry.objects.get(id=recipe_id)
    coffeeType = recipe.coffeeType

    if coffeeType.owner != request.user:
        raise Http404

    if request.method != 'POST':
        form = CoffeeRecipeEntryForm(instance=recipe)
    else:
        form = CoffeeRecipeEntryForm(instance=recipe, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('Coffee_Co:coffeeType', coffeeType_id=coffeeType.id)

    context = {'recipe': recipe, 'coffeeType': coffeeType, 'form': form}
    return render(request, 'Coffee_Co/editCoffeeRecipe.html', context)

'''No login required for this page'''
def coffee_info(request):
    return render(request, 'Coffee_Co/coffeeInfo.html')

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

# Create your views here.
def register(request):
    '''Register a new user'''
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data = request.POST)

        if form.is_valid():
            new_user = form.save()
            login(request, new_user)
            return redirect('Coffee_Co:index')

    context = {'form': form}
    return render(request, 'registration/register.html', context)

Coffee_Co/templates/Coffee_Co/base.html
{% load bootstrap4 %}
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>CoffeeCo</title>

    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
  </head>

  <body style="background-color: #f8f9fa;">
    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
      <a class="navbar-brand" href="{% url 'Coffee_Co:index' %}">
        CoffeeCo
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse"
              data-target="#navbarCollapse" aria-controls="navbarCollapse"
              aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link text-dark" href="{% url 'Coffee_Co:coffeeTypes' %}">
              Types of Coffee
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-dark" href="{% url 'Coffee_Co:coffeeInfo' %}">
              Coffee Info
            </a>
          </li>
        </ul>

        <ul class="navbar-nav ml-auto">
          {% if user.is_authenticated %}
            <li class="nav-item d-flex align-items-center">
              <span class="navbar-text text-dark mr-3 mb-0" style="position: relative; top: 2px;">
                Hello, {{ user.username }}.
              </span>
            </li>
            <li class="nav-item d-flex align-items-center">
              <form action="{% url 'users:logout' %}" method="post" class="m-0">
                {% csrf_token %}
                <button type="submit"
                        class="btn btn-link nav-link p-0 text-dark"
                        style="line-height: normal;">
                  Log Out
                </button>
              </form>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link text-dark" href="{% url 'users:register' %}">Register</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-dark" href="{% url 'users:login' %}">Log in</a>
            </li>
          {% endif %}
        </ul>
      </div>
    </nav>

    <main role="main" class="container">
      <div class="pb-2 mb-2 border-bottom">
        {% block page_header %}{% endblock page_header %}
      </div>

      <div>
        {% block content %}{% endblock content %}
        <img src="{% static 'header.png' %}" alt="Header overlay" 
             style="position: absolute; top: 0; left: 0; width: 100%; height: 60px; object-fit: cover; opacity: 0.5; pointer-events: none; z-index: 0;" />
      </div>
    </main>
  </body>
</html>

Coffee_Co/templates/Coffee_Co/coffeeInfo.html
{% extends "Coffee_Co/base.html" %}

{% block page_header %}
<h1 style='text-align: center'>Basic Coffee Types</h1>
{% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <h2>Long Black</h2>
      <p>
        A Long Black is made by pouring a double shot of espresso over hot water. It’s strong and smooth, with a rich crema on top. Popular in Australia and New Zealand.<br>
        <strong>Ratio:</strong> 1 part espresso (double shot) to 2 parts hot water (approx. 1:2).
      </p>

      <h2>Flat White</h2>
      <p>
        A Flat White is an espresso-based drink with steamed milk and a thin layer of velvety microfoam. It has a strong coffee flavor and creamy texture, perfect for those who want a balanced taste.<br>
        <strong>Ratio:</strong> 1 part espresso (double shot) to 3 parts steamed milk with microfoam (approx. 1:3).
      </p>

      <h2>Cappuccino</h2>
      <p>
        A Cappuccino combines equal parts espresso, steamed milk, and milk foam. It has a bold coffee taste with a thick frothy top, often dusted with cocoa or cinnamon.<br>
        <strong>Ratio:</strong> 1 part espresso to 1 part steamed milk to 1 part milk foam (1:1:1).
      </p>

      <h2>Latte</h2>
      <p>
        A Latte contains espresso with a larger amount of steamed milk and a small layer of foam. It’s creamier and milder than a cappuccino, ideal for those who prefer a smooth, milky coffee.<br>
        <strong>Ratio:</strong> 1 part espresso to 5 parts steamed milk with a small foam layer (approx. 1:5).
      </p>
    </div>
  </div>
</div>
{% endblock %}

Coffee_Co/templates/Coffee_Co/coffeeType.html
{% extends "Coffee_Co/base.html" %}

{% block content %}
<p>Coffee Type: {{coffeeType}}</p>
<p>
    <a href="{% url 'Coffee_Co:newCoffeeRecipe' coffeeType.id %}">Add a new recipe</a>
</p>
<ul>
    {% for entry in entries %}
    <li>
        <p>{{ entry.date_added|date:'M d, Y H:i' }}</p>
        <p>{{entry.text | linebreaks}}</p>
        <p>
           <a href="{% url 'Coffee_Co:editCoffeeRecipe' entry.id %}">Edit Recipe</a>

        </p>
    </li>
    {% empty %}
    <li>There are no recipes for this coffee type yet.</li>
    {% endfor %}
</ul>

{% endblock content %}

Coffee_Co/templates/Coffee_Co/coffeeTypes.html
{% extends "Coffee_Co/base.html" %}


{% block content %}
<p>Coffee Types</p>

<ul>
    {% for coffeeType in coffeeTypes %}
    <li>
        <a href = "{% url 'Coffee_Co:coffeeType' coffeeType.id %}">{{coffeeType}}</a>
    </li>
    {% empty %}
    <li>No coffee types have been added yet.</li>
    {% endfor %}
</ul>
<a href = "{% url 'Coffee_Co:newCoffeeType' %}">Add a new coffee type</a>


{% endblock content %}

Coffee_Co/templates/Coffee_Co/editCoffeeRecipe.html
{% extends "Coffee_Co/base.html" %}

{% block content %}
<p><a href="{% url 'Coffee_Co:coffeeType' coffeeType.id %}">{{ coffeeType }}</a></p>
<p>Edit Recipe:</p>

<form action="{% url 'Coffee_Co:editCoffeeRecipe' recipe.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="Submit">Save Changes</button>
</form>

{% endblock %}

Coffee_Co/templates/Coffee_Co/index.html
{% extends "Coffee_Co/base.html" %}
{% block page_header %}
  <div class="bg-dark text-white text-center py-5">
    <h1 class="display-4">CoffeeCo helps you keep track of your coffee recipes!</h1>
    <p class="lead">Create coffee recipes for various types of coffee and rate each recipe on a scale from 1 to 5.</p>
    <a class="btn btn-lg btn-outline-light" href="{% url 'users:register' %}" role="button">Register &raquo;</a>
  </div>
{% endblock page_header %}

Coffee_Co/templates/Coffee_Co/newCoffeeRecipe.html
{% extends "Coffee_Co/base.html" %}

{% block content %}
  <form action="{% url 'Coffee_Co:newCoffeeRecipe' coffeeType.id %}" method="post">
    {% csrf_token %}

    <p>{{ form.text.label_tag }}<br>
       {{ form.text }}</p>

    <p>{{ form.rating.label_tag }}<br>
       {% for radio in form.rating %}
         {{ radio.tag }} {{ radio.choice_label }}
       {% endfor %}
    </p>

    <button name="submit">Add Recipe</button>
  </form>
{% endblock %}

Coffee_Co/templates/Coffee_Co/newCoffeeType.html
{% extends "Coffee_Co/base.html" %}

{% block content %}
<p>Add a new coffee type:</p>
<form action="{% url 'Coffee_Co:newCoffeeType' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Add coffee type</button>
</form>
{% endblock content %}